import type { IdeaLensWorkspace } from "./types";

export const mockWorkspace: IdeaLensWorkspace = {
  idea: "AI copilot for small e-commerce stores in LatAm that writes product descriptions and email campaigns.",
  region: "LatAm",
  businessModel: "SaaS",
  goal: "Validate demand",
  snapshot: {
    problem:
      "Small e-commerce stores struggle to produce high-converting product copy consistently.",
    customer: "Small Shopify sellers in LatAm",
    solution:
      "AI copilot that generates product descriptions and email campaigns tailored to each store.",
    category: "B2B SaaS",
    wedge: "Product descriptions first",
    monetization: "$29/month subscription",
    mainAssumption:
      "Sellers will pay monthly for copy that converts better than what they write themselves.",
    validationPriority: "Test willingness to pay before building.",
  },
  selectedPersonaId: null,
  personas: [
    {
      id: "p1",
      name: "Solo Shopify Seller",
      description: "Runs a small online store alone, handles all marketing.",
      painIntensity: "High",
      budgetLevel: "Medium",
      urgency: "High",
      acquisitionChannel: "Shopify communities, TikTok, WhatsApp groups",
      objections: ["Already uses ChatGPT", "Does not want another monthly tool"],
    },
    {
      id: "p2",
      name: "Instagram Store Owner",
      description: "Sells through Instagram and WhatsApp, no formal store.",
      painIntensity: "Medium",
      budgetLevel: "Low",
      urgency: "Medium",
      acquisitionChannel: "Instagram creators, WhatsApp communities",
      objections: ["Low willingness to pay", "Prefers manual posting"],
    },
    {
      id: "p3",
      name: "Small Brand Operator",
      description: "Manages a growing DTC brand with frequent product launches.",
      painIntensity: "High",
      budgetLevel: "Medium",
      urgency: "High",
      acquisitionChannel: "E-commerce newsletters, Shopify partners",
      objections: ["Needs brand voice control", "May already use marketing tools"],
    },
  ],
  assumptions: [
    {
      id: "a1",
      text: "Small stores will pay $29/month for better product copy.",
      category: "Monetization",
      importance: "High",
      status: "Unknown",
      testMethod: "Pricing interviews + fake-door landing page",
    },
    {
      id: "a2",
      text: "Writing product descriptions is a frequent, repeated pain — not a one-time task.",
      category: "Problem",
      importance: "High",
      status: "Unknown",
      testMethod: "Customer discovery interviews",
    },
    {
      id: "a3",
      text: "Shopify sellers in LatAm are reachable through online communities.",
      category: "Distribution",
      importance: "Medium",
      status: "Unknown",
      testMethod: "Cold outreach test in 3 communities",
    },
    {
      id: "a4",
      text: "The product can differentiate from generic AI writing tools like ChatGPT.",
      category: "Market",
      importance: "High",
      status: "Unknown",
      testMethod: "Competitor messaging comparison",
    },
    {
      id: "a5",
      text: "Users care more about conversion-focused copy than generic content generation.",
      category: "Solution",
      importance: "High",
      status: "Unknown",
      testMethod: "Landing page headline A/B test",
    },
  ],
  experiments: [
    {
      id: "e1",
      title: "Interview 10 Shopify sellers",
      hypothesis: "Shopify sellers struggle with product copy every week.",
      method: "Short discovery interviews via WhatsApp or Zoom.",
      successMetric: "7 of 10 confirm this is a repeated pain.",
      effort: "Medium",
      cost: "Free",
      duration: "2 days",
      status: "This Week",
    },
    {
      id: "e2",
      title: "Fake-door pricing test",
      hypothesis: "Stores are willing to pay at least $29/month.",
      method: "Simple landing page with pricing CTA and waitlist.",
      successMetric: "5% of visitors click the pricing CTA.",
      effort: "Medium",
      cost: "Low",
      duration: "3 days",
      status: "Backlog",
    },
    {
      id: "e3",
      title: "Concierge MVP with 5 stores",
      hypothesis: "Users accept AI-generated copy when edited for brand voice.",
      method: "Manually generate descriptions for 5 stores, deliver over WhatsApp.",
      successMetric: "3 stores ask to repeat the service.",
      effort: "High",
      cost: "Free",
      duration: "5 days",
      status: "Backlog",
    },
    {
      id: "e4",
      title: "Landing page headline A/B test",
      hypothesis: "Conversion-focused messaging outperforms generic AI copy messaging.",
      method: "Test two headlines on a simple landing page.",
      successMetric: "Conversion-focused headline gets 30% more CTA clicks.",
      effort: "Low",
      cost: "Low",
      duration: "2 days",
      status: "Backlog",
    },
  ],
  scorecard: {
    overallScore: 52,
    decision: "Validate First",
    biggestRisk: "Willingness to pay is unproven. Sellers may prefer free tools.",
    recommendedNextStep: "Run 10 pricing interviews this week before writing any code.",
    dimensions: {
      problemClarity: 7,
      customerSpecificity: 5,
      urgency: 7,
      differentiation: 4,
      monetizationClarity: 4,
      mvpFeasibility: 7,
      distributionFeasibility: 6,
      evidenceStrength: 2,
    },
  },
  interviewScript: null,
  agentState: {
    status: "WaitingForUser",
    currentObjective: "Help the founder narrow the ICP and test willingness to pay.",
    confidence: 52,
    suggestions: [
      "Select a persona to sharpen the validation focus.",
      "Mark your riskiest assumption to generate a targeted experiment.",
      "Generate an interview script to start talking to customers this week.",
    ],
    activityLog: [] as string[],
    isMockActive: false,
  },
};
